name: Build OfflineCatalogApp

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-14

    env:
      THEOS: /tmp/theos

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add Theos bin to PATH
        run: echo "/tmp/theos/bin" >> $GITHUB_PATH

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install ldid dpkg make unzip zip

      - name: Clone Theos if not present
        run: |
          if [ ! -d "$THEOS" ]; then
            echo "Cloning Theos to $THEOS"
            git clone --recursive https://github.com/theos/theos.git "$THEOS"
          else
            echo "Theos already exists at $THEOS"
          fi

      - name: Debug: List Theos directory
        run: ls -al $THEOS

      - name: Build tweak with Theos
        shell: bash
        run: |
          echo "Listing contents of THEOS before sourcing setup.sh"
          ls -al $THEOS
          source "$THEOS/setup.sh"
          make clean
          make

      - name: Run build.sh to package app
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp.ipa
          path: OfflineCatalogApp.ipa
