name: Build and Package OfflineCatalogApp

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build OfflineCatalogApp
        run: |
          xcodebuild -scheme OfflineCatalogApp -configuration Release -derivedDataPath build

      - name: Install ldid (if not preinstalled)
        run: |
          if ! command -v ldid &> /dev/null; then
            brew install ldid
          fi

      - name: Run build.sh to package app
        run: chmod +x ./build.sh && ./build.sh

      - name: Upload build artifact (IPA)
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp-IPA
          path: OfflineCatalogApp-v4.ipa
