name: Build and Package OfflineCatalogApp

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install ldid dpkg make clang unzip zip

      - name: Clone Theos
        run: |
          git clone --depth=1 https://github.com/theos/theos.git $HOME/theos

      - name: Set THEOS environment variables
        shell: bash
        run: |
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV
          echo "SDKVERSION=15.2" >> $GITHUB_ENV

      - name: Build the app with Theos
        run: ./build.sh

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp-ipa
          path: OfflineCatalogApp.ipa
