jobs:
  build:
    runs-on: macos-14

    env:
      THEOS: ${{ env.HOME }}/theos

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add Theos bin to PATH
        run: echo "${{ env.THEOS }}/bin" >> $GITHUB_PATH

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install ldid dpkg make unzip zip

      - name: Clone Theos if missing
        run: |
          if [ ! -d "$THEOS" ]; then
            echo "Cloning Theos to $THEOS"
            git clone --recursive https://github.com/theos/theos.git "$THEOS"
          else
            echo "Theos already exists at $THEOS"
          fi

      - name: Debug: List Theos directory
        run: ls -al $THEOS

      - name: Build tweak with Theos
        shell: bash
        run: |
          echo "Listing THEOS contents before sourcing setup.sh"
          ls -al $THEOS
          source "$THEOS/setup.sh"
          make clean
          make
