name: Build and Package OfflineCatalogApp

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install ldid dpkg make unzip zip

      - name: Clone Theos
        run: |
          git clone --depth=1 https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Build with Theos
        env:
          THEOS: ${{ env.THEOS }}
          PATH: ${{ env.PATH }}
        run: |
          cd $GITHUB_WORKSPACE
          make clean
          make install

      - name: Package .ipa
        run: |
          APP_NAME="OfflineCatalogApp"
          PAYLOAD_DIR="Payload"
          IPA_NAME="${APP_NAME}.ipa"
          ENTITLEMENTS="entitlements.plist"

          rm -rf "$PAYLOAD_DIR" "$IPA_NAME"

          if [ ! -d "${APP_NAME}.app" ]; then
            echo "Error: ${APP_NAME}.app not found"
            exit 1
          fi

          mkdir -p "$PAYLOAD_DIR"
          cp -r "${APP_NAME}.app" "$PAYLOAD_DIR/"

          if ! command -v ldid &> /dev/null; then
            echo "Error: ldid is not installed."
            exit 1
          fi

          ldid -S"$ENTITLEMENTS" "$PAYLOAD_DIR/${APP_NAME}.app/${APP_NAME}"

          zip -r "$IPA_NAME" "$PAYLOAD_DIR"
          rm -rf "$PAYLOAD_DIR"

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp-IPA
          path: OfflineCatalogApp.ipa
