name: Build OfflineCatalogApp

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    env:
      THEOS: /tmp/theos
      PATH: /tmp/theos/bin:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify tar exists
        run: |
          echo "Checking tar binary location and version"
          which tar
          tar --version

      - name: Install Homebrew dependencies
        run: |
          brew update || true
          brew install ldid dpkg make unzip zip || true

      - name: Clone Theos if missing
        run: |
          if [ ! -d "$THEOS" ]; then
            git clone --depth=1 https://github.com/theos/theos.git "$THEOS"
          fi

      - name: Build tweak with Theos
        shell: bash
        run: |
          source "$THEOS/setup.sh"
          make clean
          make

      - name: Run build script to package app
        run: ./build.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: OfflineCatalogApp.ipa
          path: OfflineCatalogApp.ipa
