name: Build and Package OfflineCatalogApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ runner.temp }}/theos

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install ldid dpkg make unzip zip git

      - name: Clone Theos
        run: |
          if [ ! -d "${{ env.THEOS }}" ]; then
            git clone --depth=1 https://github.com/theos/theos.git "${{ env.THEOS }}"
          fi
          ls -la "${{ env.THEOS }}"
        shell: bash

      - name: Build tweak using Theos
        shell: bash
        env:
          THEOS: ${{ env.THEOS }}
          PATH: ${{ env.THEOS }}/bin:$PATH
        run: |
          source $THEOS/setup.sh
          make clean
          make

      - name: Run build.sh to package IPA
        run: ./build.sh

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp.ipa
          path: OfflineCatalogApp.ipa
