name: Build with Theos

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install ldid dpkg make clang

      - name: Clone Theos
        run: |
          git clone --depth=1 https://github.com/theos/theos.git ~/theos

      - name: Set THEOS env vars
        run: |
          echo "export THEOS=~/theos" >> $GITHUB_ENV
          echo "export PATH=\$THEOS/bin:\$PATH" >> $GITHUB_ENV
          echo "export SDKVERSION=15.2" >> $GITHUB_ENV

      - name: Build with Theos
        run: |
          make -C ./path_to_your_theos_project clean
          make -C ./path_to_your_theos_project

      - name: Package and sign .app
        run: |
          # Kopier .app, signér med ldid, pak som ipa osv.

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp-ipa
          path: OfflineCatalogApp.ipa
