name: Build and Package OfflineCatalogApp

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install ldid dpkg make unzip zip
          # clang følger med macOS, så det behøver du ikke installere

      - name: Setup Theos environment
        run: |
          git clone --depth=1 https://github.com/theos/theos.git $HOME/theos
          export THEOS=$HOME/theos
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "export PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Build app with Theos
        run: |
          source $HOME/theos/setup.sh
          make clean
          make install

      - name: Prepare Payload and sign app
        run: |
          APP_NAME="OfflineCatalogApp"
          APP_DIR="./obj/iphoneos/$APP_NAME.app"  # Theos default output path
          PAYLOAD_DIR="./Payload"
          IPA_NAME="$APP_NAME.ipa"
          ENTITLEMENTS="entitlements.plist"

          echo "Step 1: Clean up old artifacts"
          rm -rf "$PAYLOAD_DIR" "$IPA_NAME"

          echo "Step 2: Check if app directory exists"
          if [ ! -d "$APP_DIR" ]; then
            echo "Error: $APP_DIR does not exist. Build failed?"
            exit 1
          fi

          echo "Step 3: Create Payload directory and copy .app"
          mkdir -p "$PAYLOAD_DIR"
          cp -r "$APP_DIR" "$PAYLOAD_DIR/"

          echo "Step 4: Sign the app with ldid"
          ldid -S"$ENTITLEMENTS" "$PAYLOAD_DIR/$APP_NAME.app/$APP_NAME"

          echo "Step 5: Package Payload into .ipa file"
          zip -r "$IPA_NAME" "$PAYLOAD_DIR"

          echo "Step 6: Cleanup"
          rm -rf "$PAYLOAD_DIR"

          echo "Build complete! Generated $IPA_NAME"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp-IPA
          path: OfflineCatalogApp.ipa
