name: Build IPA

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ldid
        run: brew install ldid
      - name: Run build.sh
        run: |
          chmod +x build.sh
          ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: OfflineCatalogApp.ipa
          path: OfflineCatalogApp.ipa
