name: Build OfflineCatalogApp with Theos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: /tmp/theos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install ldid dpkg make unzip zip git

      - name: Clone Theos if not present
        run: |
          if [ ! -d "$THEOS" ]; then
            git clone --depth=1 https://github.com/theos/theos.git "$THEOS"
          else
            echo "Theos already cloned"
          fi

      - name: List Theos directory contents
        run: ls -la $THEOS

      - name: Build tweak with Theos
        shell: bash
        env:
          THEOS: /tmp/theos
          PATH: /tmp/theos/bin:$PATH
        run: |
          source $THEOS/setup.sh
          make clean
          make

      - name: Run build.sh to create IPA
        run: ./build.sh

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp.ipa
          path: OfflineCatalogApp.ipa
