name: Build OfflineCatalogApp

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    env:
      THEOS: /tmp/theos
      PATH: /tmp/theos/bin:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ldid dpkg make unzip zip || true
          # tar burde være installeret på macos-latest, men check:
          which tar

      - name: Clone Theos if missing
        run: |
          if [ ! -d "$THEOS" ]; then
            git clone --depth=1 https://github.com/theos/theos.git "$THEOS"
          fi

      - name: Build tweak with Theos
        shell: bash
        run: |
          source "$THEOS/setup.sh"
          make clean
          make

      - name: Package IPA
        run: ./build.sh

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp.ipa
          path: OfflineCatalogApp.ipa
