name: Build IPA

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ldid
        run: brew install ldid

      - name: Build IPA
        run: |
          chmod +x build.sh
          ./build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp
          path: OfflineCatalogApp.ipa
