name: Build OfflineCatalogApp

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-14

    env:
      THEOS: /tmp/theos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set PATH for Theos
        run: echo "/tmp/theos/bin" >> $GITHUB_PATH

      - name: Debug: List workspace contents
        run: |
          echo "Workspace root:"
          ls -al $GITHUB_WORKSPACE
          echo "Check build.sh presence:"
          ls -l ./build.sh

      - name: Debug: Check environment and tools availability
        run: |
          echo "PATH: $PATH"
          which tar || echo "tar missing"
          tar --version || echo "tar version missing"
          which git || echo "git missing"
          which make || echo "make missing"

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install ldid dpkg make unzip zip || echo "Failed to install one or more dependencies"

      - name: Debug: Check versions of installed tools
        run: |
          ldid -v
          dpkg --version
          make --version
          git --version

      - name: Clone Theos repository if missing
        run: |
          if [ ! -d "$THEOS" ]; then
            git clone --recursive https://github.com/theos/theos.git "$THEOS"
          else
            echo "Theos directory already exists"
          fi

      - name: Debug: List Theos directory
        run: ls -al $THEOS

      - name: Build tweak using Theos
        shell: bash
        run: |
          source "$THEOS/setup.sh"
          make clean
          make

      - name: Debug: List all files after build
        run: ls -al

      - name: Run build.sh to package the app
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Debug: List files after build.sh
        run: ls -al

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineCatalogApp.ipa
          path: OfflineCatalogApp.ipa

      - name: Confirm artifact upload
        run: echo "Artifact upload completed"
